/**
 * TUI theme derived from Sentry's real design tokens.
 *
 * Hex values come from `sentry/static/app/utils/theme/scraps/tokens/color.tsx`
 * (the autogenerated ramp) and the level map mirrors
 * `sentry/static/app/components/events/errorLevel.tsx`.
 */

export interface Theme {
  /** App background. */
  bg: string;
  /** Panel surfaces — one step up from the background. */
  panel: string;
  /** Secondary panel surface, for header/status chrome. */
  panelAlt: string;
  /** Row highlight for the selected item. */
  selected: string;
  border: string;
  borderFocused: string;

  text: string;
  /** Secondary/dim text — culprits, metadata, hints. */
  muted: string;
  /** Sentry blurple. */
  accent: string;

  danger: string;
  warning: string;
  success: string;

  /** Issue severity colors, keyed by `Level`. */
  level: Record<LevelKey, string>;
  /** Issue status tag colors, keyed by the badge variants Sentry uses. */
  status: {
    resolved: string;
    regressed: string;
    escalating: string;
    new: string;
    ongoing: string;
    archived: string;
  };
}

export type LevelKey =
  | "error"
  | "fatal"
  | "info"
  | "warning"
  | "sample"
  | "unknown";

export const darkTheme: Theme = {
  bg: "#0D0A10", // neutral.dark.100
  panel: "#1B1821", // neutral.dark.300
  panelAlt: "#24202B", // neutral.dark.400
  selected: "#2E2936", // neutral.dark.500
  border: "#393442", // neutral.dark.600
  borderFocused: "#7553FF", // blurple

  text: "#E7E5EA", // neutral.dark.1500
  muted: "#A49EAE", // neutral.dark.1100
  accent: "#7553FF", // blurple — Sentry primary

  danger: "#F6938C", // red.dark.1200
  warning: "#FFCE00", // yellow.dark.1200
  success: "#5ECE73", // green.dark.1200

  // errorLevel.tsx: sample/info -> accent, warning -> meh, error -> orange,
  // fatal -> bad, unknown -> other.
  level: {
    fatal: "#C10000",
    error: "#FF9838",
    warning: "#FFCE00",
    info: "#7553FF",
    sample: "#7553FF",
    unknown: "#958E9F",
  },

  // statusBadge.tsx getBadgeProperties()
  status: {
    resolved: "#5ECE73",
    regressed: "#9A94F1",
    escalating: "#F6938C",
    new: "#FFCE00",
    ongoing: "#A49EAE",
    archived: "#A49EAE",
  },
};

export const theme = darkTheme;
