/**
 * TUI theme derived from Sentry's real design tokens.
 *
 * Hex values come from `sentry/static/app/utils/theme/scraps/tokens/color.tsx`
 * (the autogenerated ramp) and the level map mirrors
 * `sentry/static/app/components/events/errorLevel.tsx`.
 */

export interface Theme {
  /** Palette identity, used to cache native color resources by mode. */
  mode: ThemeMode;
  /** App background. */
  bg: string;
  /** Panel surfaces — one step up from the background. */
  panel: string;
  /** Secondary panel surface, for header/status chrome. */
  panelAlt: string;
  /**
   * The chip pill: its surface and the two rim tints that give it an edge.
   *
   * Its own group rather than a reuse of `panelAlt`, because a chip is the one
   * thing in the app you can press and the surface now says so on its own —
   * `panelAlt` stays what header and status chrome wear.
   */
  chip: {
    /** The filled cell behind a chip's label. */
    surface: string;
    /** Top edge and both caps — the pill's lit side. */
    rim: string;
    /** The edge under the pill, a step down from `rim`. */
    rimShadow: string;
  };
  /** Row highlight for the selected item. */
  selected: string;
  border: string;
  borderFocused: string;

  text: string;
  /** Secondary/dim text — culprits, metadata, hints. */
  muted: string;
  /** One step below `muted`, for absent-value placeholders. */
  subText: string;
  /** Sentry blurple. */
  accent: string;

  danger: string;
  warning: string;
  success: string;
  /**
   * Sentry pink — the status bar's own voice, worn by every notice that isn't
   * a failure. Deliberately not the `1200` tint the other semantic colors use:
   * at that step pink lands next to `danger`'s salmon, and those two take turns
   * in the same slot, so they must never be mistaken for each other.
   */
  highlight: string;
  /**
   * The glyph inside a `(k)` key hint — the same pink, doing a different job.
   *
   * Keys are scattered across chips, the nav rail and the status bar, so the
   * only thing tying them together is that they share a color no prose uses.
   * Kept as its own token because the two roles can be retuned apart.
   */
  hotkey: string;

  /** Tree-sitter token colors. */
  syntax: SyntaxPalette;
  /** Issue severity colors, keyed by `Level`. */
  level: Record<LevelKey, string>;
  /** Issue status tag colors, keyed by the badge variants Sentry uses. */
  status: {
    resolved: string;
    regressed: string;
    escalating: string;
    new: string;
    ongoing: string;
    archived: string;
  };
}

export type ThemeMode = "dark" | "light";
export type ThemePreference = "auto" | ThemeMode;

export interface SyntaxPalette {
  keyword: string;
  string: string;
  number: string;
  comment: string;
  function: string;
  type: string;
  variable: string;
  constant: string;
  operator: string;
  punctuation: string;
}

export type LevelKey = "error" | "fatal" | "info" | "warning" | "sample" | "unknown";

/** pink.dark.1000 — the ramp's brand anchor step, named once so the two roles that wear it can't drift. */
const PINK = "#FF45A8";

export const darkTheme: Theme = {
  mode: "dark",
  bg: "#0D0A10", // neutral.dark.100
  panel: "#1B1821", // neutral.dark.300
  panelAlt: "#24202B", // neutral.dark.400
  chip: {
    // A hair short of `neutral.dark.500` (#2E2936), which is where this
    // surface wants to be. At the true step the pink key hint lands at 4.49:1
    // and the parens around it at 4.47:1 — both a rounding error below the
    // 4.5:1 this palette holds every surface to, and a key you have to read
    // before you press it is the last thing to let slip. This is the lightest
    // value that clears it: 4.55:1 and 4.53:1, indistinguishable from 500.
    surface: "#2D2835",
    rim: "#46404F", // neutral.dark.700
    rimShadow: "#393442", // neutral.dark.600
  },
  // The web tints a selected row with a translucent overlay; a terminal cell
  // needs an opaque value, so this is `neutral.dark.transparent300`
  // (#D0B8F821) composited over `bg`. The nearest opaque step, #2E2936, is
  // light enough that accent-on-selected drops to 2.99:1.
  selected: "#26212E",
  border: "#393442", // neutral.dark.600
  borderFocused: "#7553FF", // blurple

  text: "#E7E5EA", // neutral.dark.1500
  muted: "#A49EAE", // neutral.dark.1100
  subText: "#958E9F", // neutral.dark.1000
  accent: "#7553FF", // blurple — Sentry primary

  danger: "#F6938C", // red.dark.1200
  warning: "#FFCE00", // yellow.dark.1200
  success: "#5ECE73", // green.dark.1200
  highlight: PINK,
  hotkey: PINK,

  syntax: {
    keyword: "#F6938C",
    string: "#5ECE73",
    number: "#FF9838",
    comment: "#A49EAE",
    function: "#9A94F1",
    type: "#FFCE00",
    variable: "#E7E5EA",
    constant: "#FF9838",
    operator: "#A49EAE",
    punctuation: "#A49EAE",
  },

  // errorLevel.tsx: sample/info -> accent, warning -> meh, error -> orange,
  // fatal -> bad, unknown -> other.
  level: {
    fatal: "#C10000",
    error: "#FF9838",
    warning: "#FFCE00",
    info: "#7553FF",
    sample: "#7553FF",
    unknown: "#958E9F",
  },

  // statusBadge.tsx getBadgeProperties()
  status: {
    resolved: "#5ECE73",
    regressed: "#9A94F1",
    escalating: "#F6938C",
    new: "#FFCE00",
    ongoing: "#A49EAE",
    archived: "#A49EAE",
  },
};

export const lightTheme: Theme = {
  mode: "light",
  bg: "#FFFFFF",
  panel: "#F8F8F9", // neutral.light.opaque100
  // The official 200 step lands just under the surface-separation threshold.
  panelAlt: "#EEEEF0",
  chip: {
    // Between neutral 200 and 300: light enough for subText, dark enough to
    // remain a distinct control on white.
    surface: "#E8E8EB",
    rim: "#CDCCD2", // neutral.light.opaque500
    rimShadow: "#B1AFB8", // neutral.light.opaque700
  },
  selected: "#E8E8EB",
  border: "#C0BEC6", // neutral.light.opaque600
  borderFocused: "#5827D6", // blue.light.opaque1200

  text: "#302E36", // neutral.light.opaque1500
  muted: "#5B5864", // neutral.light.opaque1200
  subText: "#6A6772", // neutral.light.opaque1100
  accent: "#5827D6", // blue.light.opaque1200

  danger: "#C10000", // red.light.opaque1200
  warning: "#813100", // yellow.light.opaque1300
  success: "#007800", // green.light.opaque1200
  highlight: "#9F005F", // pink.light.opaque1300
  hotkey: "#9F005F",

  syntax: {
    keyword: "#C10000",
    string: "#007800",
    number: "#934100",
    comment: "#5B5864",
    function: "#5533B2",
    type: "#813100",
    variable: "#302E36",
    constant: "#C10000",
    operator: "#5B5864",
    punctuation: "#5B5864",
  },

  level: {
    fatal: "#780000",
    error: "#C10000",
    warning: "#813100",
    info: "#5827D6",
    sample: "#5827D6",
    unknown: "#5B5864",
  },

  status: {
    resolved: "#007800",
    regressed: "#5533B2",
    escalating: "#C10000",
    new: "#813100",
    ongoing: "#5B5864",
    archived: "#5B5864",
  },
};

/** Resolve a process-level theme preference. */
export function parseThemePreference(value: string | undefined): ThemePreference {
  const normalized = value?.trim().toLowerCase();
  if (!normalized || normalized === "auto") return "auto";
  if (normalized === "light" || normalized === "dark") return normalized;
  throw new Error("SENTRY_TUI_THEME must be auto, light, or dark");
}

/** The immutable palette for a detected or forced mode. */
export function themeFor(mode: ThemeMode): Theme {
  return mode === "light" ? lightTheme : darkTheme;
}

/**
 * Tree-sitter token styles for `<code>`, in Sentry's palette.
 *
 * Built lazily and cached: `SyntaxStyle.create` reaches into the native
 * renderer, so it must not run at module load (importing this file in a plain
 * unit test would then require a renderer).
 */
const syntaxStyles = new Map<ThemeMode, import("@opentui/core").SyntaxStyle>();

export async function getSyntaxStyle(selectedTheme: Theme) {
  const cached = syntaxStyles.get(selectedTheme.mode);
  if (cached) return cached;

  const { SyntaxStyle } = await import("@opentui/core");
  const style = SyntaxStyle.fromStyles({
    default: { fg: selectedTheme.text },
    keyword: { fg: selectedTheme.syntax.keyword },
    string: { fg: selectedTheme.syntax.string },
    number: { fg: selectedTheme.syntax.number },
    comment: { fg: selectedTheme.syntax.comment, italic: true },
    function: { fg: selectedTheme.syntax.function },
    type: { fg: selectedTheme.syntax.type },
    variable: { fg: selectedTheme.syntax.variable },
    constant: { fg: selectedTheme.syntax.constant },
    operator: { fg: selectedTheme.syntax.operator },
    punctuation: { fg: selectedTheme.syntax.punctuation },
  });
  syntaxStyles.set(selectedTheme.mode, style);
  return style;
}
