#!/usr/bin/env bun
/**
 * Rasterize Sentry's platform icons to PNG for terminal rendering.
 *
 * OpenTUI's `<image>` decodes png/jpeg/webp/gif but not SVG, and `platformicons`
 * ships SVG only. This script converts the icons the platform map actually
 * references into small PNGs, and emits two modules alongside them so neither
 * can drift from the art:
 *
 * - `packages/app/src/lib/platformIcons.generated.ts` — the platform → icon-name lookup.
 * - `packages/app/src/assets/platformIcons.generated.ts` — a static import per PNG, which is
 *   what gets the art embedded in a `bun build --compile` binary.
 *
 * All outputs are committed; this runs only when `platformicons` is upgraded.
 *
 * Requires `rsvg-convert` (`brew install librsvg`).
 */
import { $ } from "bun";
import { mkdir, readdir, rm } from "node:fs/promises";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const PKG = join(ROOT, "node_modules/platformicons");
/** The 20×20 "sm" variants — drawn for small display, which is all a cell is. */
const SVG_DIR = join(PKG, "svg");
const OUT_DIR = join(ROOT, "packages/app/src/assets/platform-icons");
const MAP_FILE = join(ROOT, "packages/app/src/lib/platformIcons.generated.ts");
const ASSET_FILE = join(ROOT, "packages/app/src/assets/platformIcons.generated.ts");

/**
 * Raster size in pixels. An icon occupies at most a few cells; at ~20px per
 * cell on a HiDPI terminal that is under 64px, so this is downsampled in
 * every real case and larger sizes only cost repo weight.
 */
const SIZE = 64;

/** A shape change in the upstream literal should fail loudly, not silently. */
const MIN_EXPECTED_PLATFORMS = 200;

/**
 * Extract `PLATFORM_TO_ICON` from the package's compiled CommonJS.
 *
 * Importing the module instead would pull in React and a `require` of all 223
 * SVGs, none of which a build script has any use for. The literal it is parsed
 * out of is itself generated, so its shape is stable.
 */
async function readPlatformMap(): Promise<Record<string, string>> {
  const source = await Bun.file(join(PKG, "build/platformIcon.js")).text();
  const marker = "exports.PLATFORM_TO_ICON = {";
  const start = source.indexOf(marker);
  if (start === -1) {
    throw new Error("PLATFORM_TO_ICON literal not found — did platformicons change its build?");
  }
  const end = source.indexOf("};", start);
  const body = source.slice(start + marker.length, end);

  const map: Record<string, string> = {};
  const entry = /^\s*(?:"([^"]+)"|([A-Za-z_$][\w$]*))\s*:\s*"([^"]+)"\s*,?\s*$/gm;
  for (const match of body.matchAll(entry)) {
    const platform = match[1] ?? match[2]!;
    map[platform] = match[3]!;
  }

  const count = Object.keys(map).length;
  if (count < MIN_EXPECTED_PLATFORMS) {
    throw new Error(`Parsed only ${count} platforms — expected at least ${MIN_EXPECTED_PLATFORMS}`);
  }
  return map;
}

/** Fail with an actionable message rather than 200 identical spawn errors. */
async function requireRsvg(): Promise<void> {
  if (!Bun.which("rsvg-convert")) {
    throw new Error("rsvg-convert not found on PATH — install it with `brew install librsvg`");
  }
}

await requireRsvg();

const platformMap = await readPlatformMap();
const iconNames = [...new Set(Object.values(platformMap))].sort();

const available = new Set(
  (await readdir(SVG_DIR)).filter((f) => f.endsWith(".svg")).map((f) => f.slice(0, -".svg".length)),
);

const missing = iconNames.filter((name) => !available.has(name));
if (missing.length > 0) {
  throw new Error(`Platform map references icons with no SVG: ${missing.join(", ")}`);
}

// Rebuild from scratch so an icon dropped upstream does not linger as a stale
// PNG that nothing references.
await rm(OUT_DIR, { recursive: true, force: true });
await mkdir(OUT_DIR, { recursive: true });

console.log(`Rasterizing ${iconNames.length} icons at ${SIZE}×${SIZE}…`);

for (const name of iconNames) {
  const input = join(SVG_DIR, `${name}.svg`);
  const output = join(OUT_DIR, `${name}.png`);
  await $`rsvg-convert -w ${SIZE} -h ${SIZE} -f png -o ${output} ${input}`.quiet();
}

const entries = Object.entries(platformMap)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([platform, icon]) => `  ${JSON.stringify(platform)}: ${JSON.stringify(icon)},`)
  .join("\n");

const module = `/**
 * GENERATED by \`bun run icons:build\` — do not edit.
 *
 * Mirrors \`PLATFORM_TO_ICON\` from the \`platformicons\` package. Every value
 * here has a matching PNG in \`packages/app/src/assets/platform-icons/\`.
 */

/** Maps a Sentry \`project.platform\` string to its icon file's base name. */
export const PLATFORM_TO_ICON: Readonly<Record<string, string>> = {
${entries}
};
`;

await Bun.write(MAP_FILE, module);

/**
 * Turn an icon base name into a unique JS identifier.
 *
 * Icon names are kebab- and dot-separated (`apache-airflow`, `node.js`), so the
 * separators collapse to underscores — which can collide, hence the guard.
 */
const identifiers = new Map<string, string>();
for (const name of iconNames) {
  const identifier = `icon_${name.replace(/\W/g, "_")}`;
  const clash = [...identifiers].find(([, id]) => id === identifier);
  if (clash) {
    throw new Error(`Icons "${clash[0]}" and "${name}" both sanitize to ${identifier}`);
  }
  identifiers.set(name, identifier);
}

const assetImports = iconNames
  .map(
    (name) =>
      `import ${identifiers.get(name)} from "./platform-icons/${name}.png" with { type: "file" };`,
  )
  .join("\n");

const assetEntries = iconNames
  .map((name) => `  ${JSON.stringify(name)}: ${identifiers.get(name)},`)
  .join("\n");

const assetModule = `/**
 * GENERATED by \`bun run icons:build\` — do not edit.
 *
 * One static import per rasterized platform icon. The imports are the point:
 * \`bun build --compile\` embeds a file only when a module imports it, so an
 * icon located by joining a path at runtime is simply absent from the
 * distributed binary. \`~/lib/platformIcons\` maps a Sentry platform onto the
 * names keyed here.
 */
${assetImports}

/** Every rasterized platform icon, keyed by its icon base name. */
export const PLATFORM_ICON_PATHS: Readonly<Record<string, string>> = {
${assetEntries}
};
`;

await Bun.write(ASSET_FILE, assetModule);

const bytes = iconNames.reduce(
  (total, name) => total + Bun.file(join(OUT_DIR, `${name}.png`)).size,
  0,
);
console.log(`Wrote ${iconNames.length} PNGs (${Math.round(bytes / 1024)} KB) to ${OUT_DIR}`);
console.log(`Wrote ${Object.keys(platformMap).length} platform mappings to ${MAP_FILE}`);
console.log(`Wrote ${iconNames.length} asset imports to ${ASSET_FILE}`);
