#!/usr/bin/env bun
/**
 * Generate the Homebrew formula for a release.
 *
 * The formula installs the prebuilt binary rather than building from source —
 * a source build would need Bun and OpenTUI's native toolchain on the user's
 * machine, which is exactly what the binary exists to avoid.
 *
 * Usage:
 *   bun run ./scripts/build-formula.ts --checksums dist/release/checksums.txt \
 *     --out dist/homebrew/sentry-tui.rb
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import {
  ARCHIVE_EXT,
  BINARY_NAME,
  RELEASE_TARGETS,
  REPOSITORY,
  type ReleaseTarget,
} from "./release-targets.ts";

const ROOT = join(import.meta.dirname, "..");

function parseFlag(name: string, fallback?: string): string {
  const index = process.argv.indexOf(`--${name}`);
  const value = index === -1 ? undefined : process.argv[index + 1];
  if (value === undefined || value.startsWith("--")) {
    if (fallback !== undefined) return fallback;
    throw new Error(`--${name} needs a value`);
  }
  return value;
}

/** Parse `<sha256>  <filename>` lines, as written by `sha256sum`/`shasum -a 256`. */
export function parseChecksums(contents: string): Map<string, string> {
  const entries = new Map<string, string>();
  for (const line of contents.split("\n")) {
    const match = line.trim().match(/^([0-9a-f]{64})\s+\*?(\S+)$/i);
    if (match?.[1] && match[2]) entries.set(match[2], match[1].toLowerCase());
  }
  return entries;
}

function assetUrl(target: ReleaseTarget, tag: string): string {
  return `https://github.com/${REPOSITORY}/releases/download/${tag}/${target.asset}.${ARCHIVE_EXT}`;
}

function block(target: ReleaseTarget, tag: string, sha: string, indent: string): string {
  return [`${indent}url "${assetUrl(target, tag)}"`, `${indent}sha256 "${sha}"`].join("\n");
}

/** Render the full formula source for `version`, given each asset's sha256. */
export function renderFormula(version: string, checksums: Map<string, string>): string {
  const tag = `v${version}`;

  const shaFor = (target: ReleaseTarget): string => {
    const sha = checksums.get(`${target.asset}.${ARCHIVE_EXT}`);
    if (!sha) throw new Error(`No checksum for ${target.asset}.${ARCHIVE_EXT}`);
    return sha;
  };

  const byKey = (key: string): ReleaseTarget => {
    const target = RELEASE_TARGETS.find((t) => t.key === key);
    if (!target) throw new Error(`Homebrew formula expects a ${key} target`);
    return target;
  };

  return `# Generated by scripts/build-formula.ts — do not edit by hand.
class SentryTui < Formula
  desc "sentry.io in your terminal — a TUI client for Sentry"
  homepage "https://github.com/${REPOSITORY}"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
${block(byKey("darwin-arm64"), tag, shaFor(byKey("darwin-arm64")), "      ")}
    end

    on_intel do
${block(byKey("darwin-x64"), tag, shaFor(byKey("darwin-x64")), "      ")}
    end
  end

  on_linux do
    on_arm do
${block(byKey("linux-arm64"), tag, shaFor(byKey("linux-arm64")), "      ")}
    end

    on_intel do
${block(byKey("linux-x64"), tag, shaFor(byKey("linux-x64")), "      ")}
    end
  end

  def install
    bin.install "${BINARY_NAME}"
  end

  test do
    assert_match "sentry.io in your terminal", shell_output("#{bin}/sentry-tui --help")
  end
end
`;
}

if (import.meta.main) {
  const checksumsPath = parseFlag("checksums", join(ROOT, "dist/release/checksums.txt"));
  const outPath = parseFlag("out", join(ROOT, "dist/homebrew/sentry-tui.rb"));

  const { version } = (await Bun.file(join(ROOT, "package.json")).json()) as { version: string };
  const checksums = parseChecksums(await Bun.file(checksumsPath).text());
  const formula = renderFormula(version, checksums);

  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, formula);

  console.log(`Formula for v${version} written to ${outPath}`);
}
