/**
 * GENERATED by `bun run icons:build` — do not edit.
 *
 * One static import per rasterized platform icon. The imports are the point:
 * `bun build --compile` embeds a file only when a module imports it, so an
 * icon located by joining a path at runtime is simply absent from the
 * distributed binary. `~/lib/platformIcons` maps a Sentry platform onto the
 * names keyed here.
 */
import icon_activeadmin from "./platform-icons/activeadmin.png" with { type: "file" };
import icon_actix from "./platform-icons/actix.png" with { type: "file" };
import icon_aiohttp from "./platform-icons/aiohttp.png" with { type: "file" };
import icon_alpinejs from "./platform-icons/alpinejs.png" with { type: "file" };
import icon_amazon from "./platform-icons/amazon.png" with { type: "file" };
import icon_amd from "./platform-icons/amd.png" with { type: "file" };
import icon_analogjs from "./platform-icons/analogjs.png" with { type: "file" };
import icon_android from "./platform-icons/android.png" with { type: "file" };
import icon_android_phone from "./platform-icons/android-phone.png" with { type: "file" };
import icon_android_tablet from "./platform-icons/android-tablet.png" with { type: "file" };
import icon_angularjs from "./platform-icons/angularjs.png" with { type: "file" };
import icon_anthropic from "./platform-icons/anthropic.png" with { type: "file" };
import icon_anthropic_claude from "./platform-icons/anthropic-claude.png" with { type: "file" };
import icon_apache_airflow from "./platform-icons/apache-airflow.png" with { type: "file" };
import icon_apache_beam from "./platform-icons/apache-beam.png" with { type: "file" };
import icon_apache_spark from "./platform-icons/apache-spark.png" with { type: "file" };
import icon_app_engine from "./platform-icons/app-engine.png" with { type: "file" };
import icon_apple from "./platform-icons/apple.png" with { type: "file" };
import icon_apple_ipad from "./platform-icons/apple-ipad.png" with { type: "file" };
import icon_apple_iphone from "./platform-icons/apple-iphone.png" with { type: "file" };
import icon_apple_tv from "./platform-icons/apple-tv.png" with { type: "file" };
import icon_apple_watch from "./platform-icons/apple-watch.png" with { type: "file" };
import icon_ariadne from "./platform-icons/ariadne.png" with { type: "file" };
import icon_arm from "./platform-icons/arm.png" with { type: "file" };
import icon_astro from "./platform-icons/astro.png" with { type: "file" };
import icon_aws from "./platform-icons/aws.png" with { type: "file" };
import icon_awslambda from "./platform-icons/awslambda.png" with { type: "file" };
import icon_azure_functions from "./platform-icons/azure-functions.png" with { type: "file" };
import icon_backbone from "./platform-icons/backbone.png" with { type: "file" };
import icon_bazzite from "./platform-icons/bazzite.png" with { type: "file" };
import icon_blazor from "./platform-icons/blazor.png" with { type: "file" };
import icon_bottle from "./platform-icons/bottle.png" with { type: "file" };
import icon_bun from "./platform-icons/bun.png" with { type: "file" };
import icon_capacitor from "./platform-icons/capacitor.png" with { type: "file" };
import icon_celery from "./platform-icons/celery.png" with { type: "file" };
import icon_chalice from "./platform-icons/chalice.png" with { type: "file" };
import icon_chrome from "./platform-icons/chrome.png" with { type: "file" };
import icon_chromium from "./platform-icons/chromium.png" with { type: "file" };
import icon_clickhouse from "./platform-icons/clickhouse.png" with { type: "file" };
import icon_clojure from "./platform-icons/clojure.png" with { type: "file" };
import icon_cloudflare from "./platform-icons/cloudflare.png" with { type: "file" };
import icon_cloudflare_pages from "./platform-icons/cloudflare-pages.png" with { type: "file" };
import icon_cloudflare_workers from "./platform-icons/cloudflare-workers.png" with { type: "file" };
import icon_cohere from "./platform-icons/cohere.png" with { type: "file" };
import icon_connect from "./platform-icons/connect.png" with { type: "file" };
import icon_convex from "./platform-icons/convex.png" with { type: "file" };
import icon_cordova from "./platform-icons/cordova.png" with { type: "file" };
import icon_cpp from "./platform-icons/cpp.png" with { type: "file" };
import icon_cryengine from "./platform-icons/cryengine.png" with { type: "file" };
import icon_crystal from "./platform-icons/crystal.png" with { type: "file" };
import icon_csharp from "./platform-icons/csharp.png" with { type: "file" };
import icon_css from "./platform-icons/css.png" with { type: "file" };
import icon_dart from "./platform-icons/dart.png" with { type: "file" };
import icon_deepseek from "./platform-icons/deepseek.png" with { type: "file" };
import icon_default from "./platform-icons/default.png" with { type: "file" };
import icon_deno from "./platform-icons/deno.png" with { type: "file" };
import icon_django from "./platform-icons/django.png" with { type: "file" };
import icon_dotnet from "./platform-icons/dotnet.png" with { type: "file" };
import icon_dotnetcore from "./platform-icons/dotnetcore.png" with { type: "file" };
import icon_dotnetframework from "./platform-icons/dotnetframework.png" with { type: "file" };
import icon_dotnetfx from "./platform-icons/dotnetfx.png" with { type: "file" };
import icon_dramatiq from "./platform-icons/dramatiq.png" with { type: "file" };
import icon_echo from "./platform-icons/echo.png" with { type: "file" };
import icon_edge from "./platform-icons/edge.png" with { type: "file" };
import icon_edge_legacy from "./platform-icons/edge-legacy.png" with { type: "file" };
import icon_effect from "./platform-icons/effect.png" with { type: "file" };
import icon_electron from "./platform-icons/electron.png" with { type: "file" };
import icon_elixir from "./platform-icons/elixir.png" with { type: "file" };
import icon_ember from "./platform-icons/ember.png" with { type: "file" };
import icon_expo from "./platform-icons/expo.png" with { type: "file" };
import icon_express from "./platform-icons/express.png" with { type: "file" };
import icon_falcon from "./platform-icons/falcon.png" with { type: "file" };
import icon_fastapi from "./platform-icons/fastapi.png" with { type: "file" };
import icon_fasthttp from "./platform-icons/fasthttp.png" with { type: "file" };
import icon_fastify from "./platform-icons/fastify.png" with { type: "file" };
import icon_fastmcp from "./platform-icons/fastmcp.png" with { type: "file" };
import icon_fiber from "./platform-icons/fiber.png" with { type: "file" };
import icon_firebase from "./platform-icons/firebase.png" with { type: "file" };
import icon_firefox from "./platform-icons/firefox.png" with { type: "file" };
import icon_flask from "./platform-icons/flask.png" with { type: "file" };
import icon_flutter from "./platform-icons/flutter.png" with { type: "file" };
import icon_font from "./platform-icons/font.png" with { type: "file" };
import icon_fsharp from "./platform-icons/fsharp.png" with { type: "file" };
import icon_gatsby from "./platform-icons/gatsby.png" with { type: "file" };
import icon_gcp_functions from "./platform-icons/gcp-functions.png" with { type: "file" };
import icon_gemini from "./platform-icons/gemini.png" with { type: "file" };
import icon_gin from "./platform-icons/gin.png" with { type: "file" };
import icon_git from "./platform-icons/git.png" with { type: "file" };
import icon_gnu from "./platform-icons/gnu.png" with { type: "file" };
import icon_go from "./platform-icons/go.png" with { type: "file" };
import icon_godot from "./platform-icons/godot.png" with { type: "file" };
import icon_google from "./platform-icons/google.png" with { type: "file" };
import icon_grape from "./platform-icons/grape.png" with { type: "file" };
import icon_graphene from "./platform-icons/graphene.png" with { type: "file" };
import icon_graphql from "./platform-icons/graphql.png" with { type: "file" };
import icon_grok from "./platform-icons/grok.png" with { type: "file" };
import icon_groq from "./platform-icons/groq.png" with { type: "file" };
import icon_grpc from "./platform-icons/grpc.png" with { type: "file" };
import icon_hanami from "./platform-icons/hanami.png" with { type: "file" };
import icon_hapi from "./platform-icons/hapi.png" with { type: "file" };
import icon_hono from "./platform-icons/hono.png" with { type: "file" };
import icon_httpx from "./platform-icons/httpx.png" with { type: "file" };
import icon_huey from "./platform-icons/huey.png" with { type: "file" };
import icon_huggingface from "./platform-icons/huggingface.png" with { type: "file" };
import icon_hydrogen from "./platform-icons/hydrogen.png" with { type: "file" };
import icon_internet_explorer from "./platform-icons/internet-explorer.png" with { type: "file" };
import icon_ionic from "./platform-icons/ionic.png" with { type: "file" };
import icon_iris from "./platform-icons/iris.png" with { type: "file" };
import icon_java from "./platform-icons/java.png" with { type: "file" };
import icon_javascript from "./platform-icons/javascript.png" with { type: "file" };
import icon_koa from "./platform-icons/koa.png" with { type: "file" };
import icon_kotlin from "./platform-icons/kotlin.png" with { type: "file" };
import icon_langchain from "./platform-icons/langchain.png" with { type: "file" };
import icon_langgraph from "./platform-icons/langgraph.png" with { type: "file" };
import icon_laravel from "./platform-icons/laravel.png" with { type: "file" };
import icon_launchdarkly from "./platform-icons/launchdarkly.png" with { type: "file" };
import icon_linux from "./platform-icons/linux.png" with { type: "file" };
import icon_lit from "./platform-icons/lit.png" with { type: "file" };
import icon_litellm from "./platform-icons/litellm.png" with { type: "file" };
import icon_litestar from "./platform-icons/litestar.png" with { type: "file" };
import icon_livewire from "./platform-icons/livewire.png" with { type: "file" };
import icon_logback from "./platform-icons/logback.png" with { type: "file" };
import icon_loguru from "./platform-icons/loguru.png" with { type: "file" };
import icon_magento from "./platform-icons/magento.png" with { type: "file" };
import icon_martini from "./platform-icons/martini.png" with { type: "file" };
import icon_mastra from "./platform-icons/mastra.png" with { type: "file" };
import icon_maui from "./platform-icons/maui.png" with { type: "file" };
import icon_mcp from "./platform-icons/mcp.png" with { type: "file" };
import icon_meteor from "./platform-icons/meteor.png" with { type: "file" };
import icon_million from "./platform-icons/million.png" with { type: "file" };
import icon_mistral from "./platform-icons/mistral.png" with { type: "file" };
import icon_mongodb from "./platform-icons/mongodb.png" with { type: "file" };
import icon_mono from "./platform-icons/mono.png" with { type: "file" };
import icon_motorola from "./platform-icons/motorola.png" with { type: "file" };
import icon_nativec from "./platform-icons/nativec.png" with { type: "file" };
import icon_nestjs from "./platform-icons/nestjs.png" with { type: "file" };
import icon_nextjs from "./platform-icons/nextjs.png" with { type: "file" };
import icon_nintendo from "./platform-icons/nintendo.png" with { type: "file" };
import icon_nintendo_switch from "./platform-icons/nintendo-switch.png" with { type: "file" };
import icon_nintendo_switch_2 from "./platform-icons/nintendo-switch-2.png" with { type: "file" };
import icon_nitro from "./platform-icons/nitro.png" with { type: "file" };
import icon_nodejs from "./platform-icons/nodejs.png" with { type: "file" };
import icon_nuxt from "./platform-icons/nuxt.png" with { type: "file" };
import icon_nvidia from "./platform-icons/nvidia.png" with { type: "file" };
import icon_openai from "./platform-icons/openai.png" with { type: "file" };
import icon_openfeature from "./platform-icons/openfeature.png" with { type: "file" };
import icon_opennext from "./platform-icons/opennext.png" with { type: "file" };
import icon_opera from "./platform-icons/opera.png" with { type: "file" };
import icon_padrino from "./platform-icons/padrino.png" with { type: "file" };
import icon_perforce from "./platform-icons/perforce.png" with { type: "file" };
import icon_perl from "./platform-icons/perl.png" with { type: "file" };
import icon_perplexity from "./platform-icons/perplexity.png" with { type: "file" };
import icon_php from "./platform-icons/php.png" with { type: "file" };
import icon_playstation from "./platform-icons/playstation.png" with { type: "file" };
import icon_postgresql from "./platform-icons/postgresql.png" with { type: "file" };
import icon_powershell from "./platform-icons/powershell.png" with { type: "file" };
import icon_pydantic_ai from "./platform-icons/pydantic-ai.png" with { type: "file" };
import icon_pyramid from "./platform-icons/pyramid.png" with { type: "file" };
import icon_python from "./platform-icons/python.png" with { type: "file" };
import icon_qq from "./platform-icons/qq.png" with { type: "file" };
import icon_qt from "./platform-icons/qt.png" with { type: "file" };
import icon_quart from "./platform-icons/quart.png" with { type: "file" };
import icon_qwik from "./platform-icons/qwik.png" with { type: "file" };
import icon_rails from "./platform-icons/rails.png" with { type: "file" };
import icon_ray from "./platform-icons/ray.png" with { type: "file" };
import icon_react from "./platform-icons/react.png" with { type: "file" };
import icon_react_native from "./platform-icons/react-native.png" with { type: "file" };
import icon_react_router from "./platform-icons/react-router.png" with { type: "file" };
import icon_redis from "./platform-icons/redis.png" with { type: "file" };
import icon_remix from "./platform-icons/remix.png" with { type: "file" };
import icon_ruby from "./platform-icons/ruby.png" with { type: "file" };
import icon_rust from "./platform-icons/rust.png" with { type: "file" };
import icon_safari from "./platform-icons/safari.png" with { type: "file" };
import icon_samsung from "./platform-icons/samsung.png" with { type: "file" };
import icon_sanic from "./platform-icons/sanic.png" with { type: "file" };
import icon_scala from "./platform-icons/scala.png" with { type: "file" };
import icon_serverless from "./platform-icons/serverless.png" with { type: "file" };
import icon_sidekiq from "./platform-icons/sidekiq.png" with { type: "file" };
import icon_sinatra from "./platform-icons/sinatra.png" with { type: "file" };
import icon_solid from "./platform-icons/solid.png" with { type: "file" };
import icon_solidstart from "./platform-icons/solidstart.png" with { type: "file" };
import icon_spring from "./platform-icons/spring.png" with { type: "file" };
import icon_springboot from "./platform-icons/springboot.png" with { type: "file" };
import icon_sql from "./platform-icons/sql.png" with { type: "file" };
import icon_sqlalchemy from "./platform-icons/sqlalchemy.png" with { type: "file" };
import icon_sqlserver from "./platform-icons/sqlserver.png" with { type: "file" };
import icon_starlette from "./platform-icons/starlette.png" with { type: "file" };
import icon_steamos from "./platform-icons/steamos.png" with { type: "file" };
import icon_strawberry from "./platform-icons/strawberry.png" with { type: "file" };
import icon_stride3d from "./platform-icons/stride3d.png" with { type: "file" };
import icon_supabase from "./platform-icons/supabase.png" with { type: "file" };
import icon_svelte from "./platform-icons/svelte.png" with { type: "file" };
import icon_swift from "./platform-icons/swift.png" with { type: "file" };
import icon_symfony from "./platform-icons/symfony.png" with { type: "file" };
import icon_tanstack from "./platform-icons/tanstack.png" with { type: "file" };
import icon_tauri from "./platform-icons/tauri.png" with { type: "file" };
import icon_tokio from "./platform-icons/tokio.png" with { type: "file" };
import icon_tornado from "./platform-icons/tornado.png" with { type: "file" };
import icon_tower from "./platform-icons/tower.png" with { type: "file" };
import icon_tracing from "./platform-icons/tracing.png" with { type: "file" };
import icon_trailblazer from "./platform-icons/trailblazer.png" with { type: "file" };
import icon_tryton from "./platform-icons/tryton.png" with { type: "file" };
import icon_typer from "./platform-icons/typer.png" with { type: "file" };
import icon_ubuntu from "./platform-icons/ubuntu.png" with { type: "file" };
import icon_unity from "./platform-icons/unity.png" with { type: "file" };
import icon_unleash from "./platform-icons/unleash.png" with { type: "file" };
import icon_uno from "./platform-icons/uno.png" with { type: "file" };
import icon_unreal from "./platform-icons/unreal.png" with { type: "file" };
import icon_vercel from "./platform-icons/vercel.png" with { type: "file" };
import icon_visual_basic from "./platform-icons/visual-basic.png" with { type: "file" };
import icon_vscode from "./platform-icons/vscode.png" with { type: "file" };
import icon_vue from "./platform-icons/vue.png" with { type: "file" };
import icon_wasm from "./platform-icons/wasm.png" with { type: "file" };
import icon_windows from "./platform-icons/windows.png" with { type: "file" };
import icon_xamarin from "./platform-icons/xamarin.png" with { type: "file" };
import icon_xbox from "./platform-icons/xbox.png" with { type: "file" };

/** Every rasterized platform icon, keyed by its icon base name. */
export const PLATFORM_ICON_PATHS: Readonly<Record<string, string>> = {
  activeadmin: icon_activeadmin,
  actix: icon_actix,
  aiohttp: icon_aiohttp,
  alpinejs: icon_alpinejs,
  amazon: icon_amazon,
  amd: icon_amd,
  analogjs: icon_analogjs,
  android: icon_android,
  "android-phone": icon_android_phone,
  "android-tablet": icon_android_tablet,
  angularjs: icon_angularjs,
  anthropic: icon_anthropic,
  "anthropic-claude": icon_anthropic_claude,
  "apache-airflow": icon_apache_airflow,
  "apache-beam": icon_apache_beam,
  "apache-spark": icon_apache_spark,
  "app-engine": icon_app_engine,
  apple: icon_apple,
  "apple-ipad": icon_apple_ipad,
  "apple-iphone": icon_apple_iphone,
  "apple-tv": icon_apple_tv,
  "apple-watch": icon_apple_watch,
  ariadne: icon_ariadne,
  arm: icon_arm,
  astro: icon_astro,
  aws: icon_aws,
  awslambda: icon_awslambda,
  "azure-functions": icon_azure_functions,
  backbone: icon_backbone,
  bazzite: icon_bazzite,
  blazor: icon_blazor,
  bottle: icon_bottle,
  bun: icon_bun,
  capacitor: icon_capacitor,
  celery: icon_celery,
  chalice: icon_chalice,
  chrome: icon_chrome,
  chromium: icon_chromium,
  clickhouse: icon_clickhouse,
  clojure: icon_clojure,
  cloudflare: icon_cloudflare,
  "cloudflare-pages": icon_cloudflare_pages,
  "cloudflare-workers": icon_cloudflare_workers,
  cohere: icon_cohere,
  connect: icon_connect,
  convex: icon_convex,
  cordova: icon_cordova,
  cpp: icon_cpp,
  cryengine: icon_cryengine,
  crystal: icon_crystal,
  csharp: icon_csharp,
  css: icon_css,
  dart: icon_dart,
  deepseek: icon_deepseek,
  default: icon_default,
  deno: icon_deno,
  django: icon_django,
  dotnet: icon_dotnet,
  dotnetcore: icon_dotnetcore,
  dotnetframework: icon_dotnetframework,
  dotnetfx: icon_dotnetfx,
  dramatiq: icon_dramatiq,
  echo: icon_echo,
  edge: icon_edge,
  "edge-legacy": icon_edge_legacy,
  effect: icon_effect,
  electron: icon_electron,
  elixir: icon_elixir,
  ember: icon_ember,
  expo: icon_expo,
  express: icon_express,
  falcon: icon_falcon,
  fastapi: icon_fastapi,
  fasthttp: icon_fasthttp,
  fastify: icon_fastify,
  fastmcp: icon_fastmcp,
  fiber: icon_fiber,
  firebase: icon_firebase,
  firefox: icon_firefox,
  flask: icon_flask,
  flutter: icon_flutter,
  font: icon_font,
  fsharp: icon_fsharp,
  gatsby: icon_gatsby,
  "gcp-functions": icon_gcp_functions,
  gemini: icon_gemini,
  gin: icon_gin,
  git: icon_git,
  gnu: icon_gnu,
  go: icon_go,
  godot: icon_godot,
  google: icon_google,
  grape: icon_grape,
  graphene: icon_graphene,
  graphql: icon_graphql,
  grok: icon_grok,
  groq: icon_groq,
  grpc: icon_grpc,
  hanami: icon_hanami,
  hapi: icon_hapi,
  hono: icon_hono,
  httpx: icon_httpx,
  huey: icon_huey,
  huggingface: icon_huggingface,
  hydrogen: icon_hydrogen,
  "internet-explorer": icon_internet_explorer,
  ionic: icon_ionic,
  iris: icon_iris,
  java: icon_java,
  javascript: icon_javascript,
  koa: icon_koa,
  kotlin: icon_kotlin,
  langchain: icon_langchain,
  langgraph: icon_langgraph,
  laravel: icon_laravel,
  launchdarkly: icon_launchdarkly,
  linux: icon_linux,
  lit: icon_lit,
  litellm: icon_litellm,
  litestar: icon_litestar,
  livewire: icon_livewire,
  logback: icon_logback,
  loguru: icon_loguru,
  magento: icon_magento,
  martini: icon_martini,
  mastra: icon_mastra,
  maui: icon_maui,
  mcp: icon_mcp,
  meteor: icon_meteor,
  million: icon_million,
  mistral: icon_mistral,
  mongodb: icon_mongodb,
  mono: icon_mono,
  motorola: icon_motorola,
  nativec: icon_nativec,
  nestjs: icon_nestjs,
  nextjs: icon_nextjs,
  nintendo: icon_nintendo,
  "nintendo-switch": icon_nintendo_switch,
  "nintendo-switch-2": icon_nintendo_switch_2,
  nitro: icon_nitro,
  nodejs: icon_nodejs,
  nuxt: icon_nuxt,
  nvidia: icon_nvidia,
  openai: icon_openai,
  openfeature: icon_openfeature,
  opennext: icon_opennext,
  opera: icon_opera,
  padrino: icon_padrino,
  perforce: icon_perforce,
  perl: icon_perl,
  perplexity: icon_perplexity,
  php: icon_php,
  playstation: icon_playstation,
  postgresql: icon_postgresql,
  powershell: icon_powershell,
  "pydantic-ai": icon_pydantic_ai,
  pyramid: icon_pyramid,
  python: icon_python,
  qq: icon_qq,
  qt: icon_qt,
  quart: icon_quart,
  qwik: icon_qwik,
  rails: icon_rails,
  ray: icon_ray,
  react: icon_react,
  "react-native": icon_react_native,
  "react-router": icon_react_router,
  redis: icon_redis,
  remix: icon_remix,
  ruby: icon_ruby,
  rust: icon_rust,
  safari: icon_safari,
  samsung: icon_samsung,
  sanic: icon_sanic,
  scala: icon_scala,
  serverless: icon_serverless,
  sidekiq: icon_sidekiq,
  sinatra: icon_sinatra,
  solid: icon_solid,
  solidstart: icon_solidstart,
  spring: icon_spring,
  springboot: icon_springboot,
  sql: icon_sql,
  sqlalchemy: icon_sqlalchemy,
  sqlserver: icon_sqlserver,
  starlette: icon_starlette,
  steamos: icon_steamos,
  strawberry: icon_strawberry,
  stride3d: icon_stride3d,
  supabase: icon_supabase,
  svelte: icon_svelte,
  swift: icon_swift,
  symfony: icon_symfony,
  tanstack: icon_tanstack,
  tauri: icon_tauri,
  tokio: icon_tokio,
  tornado: icon_tornado,
  tower: icon_tower,
  tracing: icon_tracing,
  trailblazer: icon_trailblazer,
  tryton: icon_tryton,
  typer: icon_typer,
  ubuntu: icon_ubuntu,
  unity: icon_unity,
  unleash: icon_unleash,
  uno: icon_uno,
  unreal: icon_unreal,
  vercel: icon_vercel,
  "visual-basic": icon_visual_basic,
  vscode: icon_vscode,
  vue: icon_vue,
  wasm: icon_wasm,
  windows: icon_windows,
  xamarin: icon_xamarin,
  xbox: icon_xbox,
};
